# Generated by Django 4.1.3 on 2023-01-11 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_invited'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invited',
            old_name='fr',
            new_name='fr_user',
        ),
        migrations.RenameField(
            model_name='invited',
            old_name='to',
            new_name='to_user',
        ),
    ]
