# Generated by Django 4.1.3 on 2023-01-11 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_rename_fr_invited_fr_user_rename_to_invited_to_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='inviters',
        ),
    ]
