# Generated by Django 4.1.3 on 2023-01-11 05:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_delete_inviters'),
    ]

    operations = [
        migrations.AddField(
            model_name='invited',
            name='fr_pages',
            field=models.ForeignKey(blank=True, default=True, on_delete=django.db.models.deletion.CASCADE, related_name='pagez', to='network.page'),
        ),
    ]
