# Generated by Django 3.2.8 on 2023-01-11 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_invited_fr_pages'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='cover',
            field=models.ImageField(default='card2.webp', upload_to='posts'),
        ),
    ]
