# Generated by Django 4.1.3 on 2023-01-12 12:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0008_commentz'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentz',
            name='user_post',
            field=models.ForeignKey(blank=True, default=True, on_delete=django.db.models.deletion.CASCADE, related_name='pos', to='network.post'),
        ),
        migrations.AlterField(
            model_name='commentz',
            name='fr_user',
            field=models.ForeignKey(blank=True, default=True, on_delete=django.db.models.deletion.CASCADE, related_name='comm', to=settings.AUTH_USER_MODEL),
        ),
    ]
