# Generated by Django 4.1.3 on 2023-01-13 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0009_commentz_user_post_alter_commentz_fr_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='doc',
            field=models.FileField(blank=True, default=True, upload_to='posts/'),
        ),
    ]
