# Generated by Django 4.1.3 on 2023-01-13 04:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0010_post_doc'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='vedio',
            field=models.FileField(blank=True, default=True, upload_to='posts/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['MOV', 'avi', 'mp4', 'webm', 'mkv'])]),
        ),
    ]
