# Generated by Django 4.0.5 on 2023-01-15 12:33

from django.db import migrations, models
import network.validators


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0012_alter_post_vedio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content_image',
            field=models.FileField(blank=True, default=True, upload_to='posts/', validators=[network.validators.file_size]),
        ),
    ]
