# Generated by Django 4.1.3 on 2023-01-18 05:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0013_alter_post_content_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='friend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fr', models.ForeignKey(blank=True, default=True, on_delete=django.db.models.deletion.CASCADE, related_name='freq', to=settings.AUTH_USER_MODEL)),
                ('to', models.ForeignKey(blank=True, default=True, on_delete=django.db.models.deletion.CASCADE, related_name='toreq', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
