# Generated by Django 4.1.3 on 2023-01-18 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0014_friend'),
    ]

    operations = [
        migrations.DeleteModel(
            name='friendz',
        ),
    ]
