# Generated by Django 4.1.3 on 2023-01-19 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0016_post_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='views',
            field=models.IntegerField(default=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.CharField(default=True, max_length=130),
        ),
    ]
