# Generated by Django 4.1.3 on 2023-01-19 07:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0017_post_views_alter_post_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='wishlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.ForeignKey(blank=True, default=True, on_delete=django.db.models.deletion.CASCADE, related_name='postz', to='network.post')),
                ('usr', models.ForeignKey(blank=True, default=True, on_delete=django.db.models.deletion.CASCADE, related_name='whs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
