# Generated by Django 3.2.8 on 2023-01-19 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0018_wishlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(default='static/std.jpg', upload_to='posts/'),
        ),
    ]
